name: 🚀 Desplegar Web en Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependencias
      run: npm install

    - name: Compilar el proyecto Astro
      run: npm run build

    - name: Verificar archivos construidos
      run: ls -la ./dist/

    - name: Subir a Hostinger por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/ 
        server-dir: /domains/pickleballaguilas.club/public_html/
        state-name: .sync-state-v6.json

    - name: Desplegar espejo en Netlify (Para Admin)
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: "acec68f4-3690-4cea-8b3a-426b9333fa51"
      run: npx netlify-cli deploy --dir=./dist --site=$NETLIFY_SITE_ID --prod