name: 🚀 Desplegar Web en Hostinger

on:
  push:
    branches:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependencias
      run: npm install

    - name: Compilar el proyecto Astro
      run: npm run build

    - name: Subir a Hostinger por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/ 
        server-dir: ./public_html/
        state-name: .sync-state-v2.json